'use client';
import { useEffect, useState } from 'react';
import { ArrowUp, BarChart3, CalendarDays, TrendingUp } from 'lucide-react';
import { money } from '@/lib/catalog';
type Row = { day:string; orders:number; revenue:number; discounts:number };
type Visit = { day:string; count:number };
export default function AdminReports() {
  const [period,setPeriod] = useState('30');
  const [month,setMonth] = useState('');
  const [from,setFrom] = useState('');
  const [to,setTo] = useState('');
  const [sales,setSales] = useState<Row[]>([]);
  const [visits,setVisits] = useState<Visit[]>([]);
  const [loading,setLoading] = useState(true);
  useEffect(()=>{setLoading(true);const params=new URLSearchParams();if(period==='month'&&month)params.set('month',month);else if(period==='custom'&&from&&to){params.set('from',from);params.set('to',to);}else if(['current-month','last-month'].includes(period))params.set('period',period);else params.set('days',period);fetch('/api/admin?'+params).then(r=>r.json()).then((raw:unknown)=>{const v=raw as {reports?:{sales:Row[];visits:Visit[]}};setSales(v.reports?.sales||[]);setVisits(v.reports?.visits||[]);}).finally(()=>setLoading(false));},[period,month,from,to]);
  const max = Math.max(1,...sales.map(x=>x.revenue)); const total=sales.reduce((n,x)=>n+x.revenue,0); const orders=sales.reduce((n,x)=>n+x.orders,0); const maxVisit=Math.max(1,...visits.map(x=>x.count));
  const periodLabel=period==='current-month'?'الشهر الحالي':period==='last-month'?'الشهر السابق':period==='7'?'آخر 7 أيام':period==='90'?'آخر 3 شهور':period==='365'?'آخر 365 يومًا':period==='month'?(month||'شهر محدد'):period==='custom'?(from&&to?from+' — '+to:'تاريخ مخصص'):'آخر 30 يومًا';
  return <div className="reports-page"><div className="reports-head"><div><p className="eyebrow">BE3A / REPORTS</p><h1>التحليلات والتقارير</h1><p>الأرقام المعروضة مأخوذة من الطلبات والزيارات المسجلة فعليًا.</p></div><div className="report-controls"><label className="report-range"><CalendarDays size={17}/><span>الفترة</span><select value={period} onChange={e=>setPeriod(e.target.value)} aria-label="اختيار فترة التقرير"><option value="current-month">الشهر الحالي</option><option value="last-month">الشهر السابق</option><option value="7">آخر 7 أيام</option><option value="30">آخر 30 يومًا</option><option value="90">آخر 3 شهور</option><option value="365">آخر 365 يومًا</option><option value="month">شهر محدد</option><option value="custom">تاريخ من إلى</option></select></label>{period==='month'&&<label className="report-date-field">اختاري الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}{period==='custom'&&<div className="report-date-pair"><label>من التاريخ<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى التاريخ<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}</div></div>{loading?<div className="admin-card">جاري تحميل التقرير…</div>:<><div className="report-stats"><div><BarChart3/><span>المبيعات</span><strong>{money(total)}</strong></div><div><TrendingUp/><span>الطلبات</span><strong>{orders}</strong></div><div><ArrowUp/><span>متوسط الطلب</span><strong>{money(orders?total/orders:0)}</strong></div></div><section className="admin-card chart-card"><div className="card-heading"><h2>المبيعات اليومية</h2><span>{periodLabel}</span></div><div className="bar-chart">{sales.length?sales.map(row=><div className="bar-column" key={row.day} title={row.day+': '+money(row.revenue)}><div className="bar" style={{height:Math.max(4,row.revenue/max*100)+'%'}}/><small>{row.day.slice(5)}</small></div>):<p className="notification-empty">لا توجد مبيعات مسجلة في الفترة دي.</p>}</div></section><section className="admin-card chart-card"><div className="card-heading"><h2>الزيارات اليومية</h2><span>إجمالي الفترة: {visits.reduce((n,x)=>n+x.count,0)}</span></div><div className="bar-chart visits-chart">{visits.length?visits.map(row=><div className="bar-column" key={row.day} title={row.day+': '+row.count+' زيارة'}><div className="bar" style={{height:Math.max(4,row.count/maxVisit*100)+'%'}}/><small>{row.day.slice(5)}</small></div>):<p className="notification-empty">لا توجد زيارات مسجلة في الفترة دي.</p>}</div></section></>}</div>;
}

