export type ColorVariant = { name: string; hex: string; image?: string; stock?: number };
export type Product = { images?: string[]; revision?: number; homeFeatured?: boolean; id: string; name: string; category: string; price: number; compareAtPrice?: number; image: string; description: string; sizes: string[]; colors: string[]; colorVariants?: ColorVariant[]; sizeStock?: Record<string, number>; stock: number; active: boolean; demo: boolean; featured: boolean };
export type Settings = { editorialTitle?: string; editorialText?: string; editorialImage?: string; categoryImages?: Record<string,string>; name: string; tagline: string; announcement: string; heroTitle: string; heroText: string; heroImage: string; logo: string; phone: string; email: string; instagram: string; facebook: string; telegram: string; tiktok: string; categories: string[]; shipping: {name: string; price: number; active?: boolean}[]; privacy: string; returns: string; about: string; siteEnabled: boolean; checkoutEnabled: boolean; accent: string };
export const defaults: Settings = {
 editorialTitle:'اللوك الحلو\nفي تفاصيله.',editorialText:'قطعة بسيطة، شنطة مميزة، ولمستك إنتِ. اختاري الحاجات اللي تحبي تلبسيها بطريقتك.',editorialImage:'/images/collection.png',categoryImages:{ملابس:'/images/editorial.png',شنط:'/images/category-bags.jpg',Rosjo:'/rosjo/images/categories/skin-care/category.png'}, name:'بيعة', tagline:'حاجات على ذوقك', announcement:'ستايل يشبهك، وتفاصيل تكمّلك', heroTitle:'على ذوقك.\nعلى طبيعتك.', heroText:'هدوم تحبيها، وشنطة تكمّل الحكاية. اكتشفي اختيارات بيعة لكل يوم ولكل خروجة.', heroImage:'/images/editorial.png', logo:'/images/brand-reference.png',
 phone:'+201039396897', email:'be3amarket@gmail.com', instagram:'https://www.instagram.com/be3a.market?stkn=MTZ3MGc4eGVjZ3hmaA==', facebook:'https://www.facebook.com/share/1DK54i6GAB/?mibextid=wwXIfr', telegram:'https://t.me/be3a_market', tiktok:'https://www.tiktok.com/@be3a.market?is_from_webapp=1&sender_device=pc',
 categories:['ملابس','شنط','Rosjo'], shipping:[], privacy:'نستخدم الاسم ورقم الموبايل والعنوان لتجهيز طلبك والتواصل بخصوصه. للاستفسار أو طلب حذف بياناتك تواصلي معنا على بريد المتجر.', returns:'تواصلي مع بيعة لمعرفة تفاصيل الاستبدال والاسترجاع قبل تأكيد الطلب.', about:'بيعة براند مصري أونلاين للهدوم البناتي والشنط الحريمي. بنختار تفاصيل عملية وأنيقة تكمّل ستايلك بطريقتك.', siteEnabled:true, checkoutEnabled:true, accent:'#FF6B3D'
};

/** Rosjo Pure Care launch catalog. Product images intentionally use the brand mark
 * until pack photography is supplied; the Rosjo category carries the full visual treatment. */
export const rosjoProducts: Product[] = [
 {id:'rosjo-shampoo',name:'شامبو روزجو العضوي الخالي من السلفات | Shampoo',category:'Rosjo',price:280,compareAtPrice:350,image:'/rosjo/images/products/shampoo/image-1.png',images:['/rosjo/images/products/shampoo/image-1.png','/rosjo/images/products/shampoo/image-2.png','/rosjo/images/products/shampoo/image-3.png'],description:'شامبو روزجو العضوي الخالي من السلفات مصمم لتنظيف الشعر وفروة الرأس بلطف مع الحفاظ على ترطيب الشعر ويساعد على تحسين مظهر الشعر ومنحه إحساسًا بالنظافة والانتعاش دون القسوة على الشعر',sizes:['مقاس واحد'],colors:['وردي روزجو'],colorVariants:[{name:'وردي روزجو',hex:'#d98f98',image:'/rosjo/images/products/shampoo/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-saad-oil',name:'زيت سعد الخاص لإضعاف الشعر الزائد | Saad Oil',category:'Rosjo',price:140,compareAtPrice:190,image:'/rosjo/images/products/saad-oil/image-1.png',images:['/rosjo/images/products/saad-oil/image-1.png','/rosjo/images/products/saad-oil/image-2.png','/rosjo/images/products/saad-oil/image-3.png'],description:'زيت سعد المخصص للعناية بالمناطق التي يظهر بها الشعر الزائد ويساعد مع الاستخدام المنتظم على إضعاف نمو الشعر الزائد ويمنح البشرة عناية وترطيبًا مناسبًا',sizes:['مقاس واحد'],colors:['ذهبي روزجو'],colorVariants:[{name:'ذهبي روزجو',hex:'#c89f74',image:'/rosjo/images/products/saad-oil/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-rose-oil',name:'زيت الورد النقي الطبيعي | Rose Oil',category:'Rosjo',price:160,compareAtPrice:220,image:'/rosjo/images/products/rose-oil/image-1.png',images:['/rosjo/images/products/rose-oil/image-1.png','/rosjo/images/products/rose-oil/image-2.png','/rosjo/images/products/rose-oil/image-3.png'],description:'زيت الورد الطبيعي النقي للعناية بالبشرة يساعد على ترطيب البشرة وتنعيمها ويمنحها مظهرًا صحيًا ونضارة طبيعية ويمكن استخدامه ضمن روتين العناية اليومي',sizes:['مقاس واحد'],colors:['وردي فاتح'],colorVariants:[{name:'وردي فاتح',hex:'#e7a5b5',image:'/rosjo/images/products/rose-oil/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-moisturizer',name:'مرطب الوجه المغذي | Moisturizer',category:'Rosjo',price:220,compareAtPrice:290,image:'/rosjo/images/products/moisturizer/image-1.png',images:['/rosjo/images/products/moisturizer/image-1.png','/rosjo/images/products/moisturizer/image-2.png','/rosjo/images/products/moisturizer/image-3.png'],description:'مرطب للوجه يساعد على ترطيب البشرة بعمق وتغذيتها والحفاظ على نعومتها ويمنح البشرة إحساسًا بالراحة والانتعاش ومظهرًا أكثر نضارة',sizes:['مقاس واحد'],colors:['كريمي روزجو'],colorVariants:[{name:'كريمي روزجو',hex:'#f1d9cf',image:'/rosjo/images/products/moisturizer/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-hair-serum',name:'سيروم الشعر الحريري | Hair Serum',category:'Rosjo',price:250,compareAtPrice:320,image:'/rosjo/images/products/hair-serum/image-1.png',images:['/rosjo/images/products/hair-serum/image-1.png','/rosjo/images/products/hair-serum/image-2.png','/rosjo/images/products/hair-serum/image-3.png'],description:'سيروم مخصص للعناية بالشعر يساعد على ترطيب وتنعيم الشعر وتقليل مظهر الجفاف والهيشان ويمنح الشعر مظهرًا أكثر نعومة ولمعانًا وسهولة في التصفيف',sizes:['مقاس واحد'],colors:['روزجو روز'],colorVariants:[{name:'روزجو روز',hex:'#c97986',image:'/rosjo/images/products/hair-serum/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-follicle-booster',name:'معزز نمو بصيلات الشعر | Follicle Booster',category:'Rosjo',price:250,compareAtPrice:330,image:'/rosjo/images/products/follicle-booster/image-1.png',images:['/rosjo/images/products/follicle-booster/image-1.png','/rosjo/images/products/follicle-booster/image-2.png','/rosjo/images/products/follicle-booster/image-3.png'],description:'منتج مخصص للعناية بفروة الرأس وبصيلات الشعر يساعد على دعم صحة البصيلات والعناية بالشعر من الجذور ويساعد على تحسين مظهر الشعر ودعم روتين العناية به',sizes:['مقاس واحد'],colors:['وردي غامق'],colorVariants:[{name:'وردي غامق',hex:'#aa596c',image:'/rosjo/images/products/follicle-booster/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-cleanser',name:'غسول الوجه المنظف والمنعش | Facial Cleanser',category:'Rosjo',price:230,compareAtPrice:300,image:'/rosjo/images/products/cleanser/image-1.png',images:['/rosjo/images/products/cleanser/image-1.png','/rosjo/images/products/cleanser/image-2.png','/rosjo/images/products/cleanser/image-3.png'],description:'غسول للوجه يساعد على تنظيف البشرة من الأوساخ والشوائب والزيوت الزائدة وينعش البشرة ويتركها أكثر نظافة وانتعاشًا ومناسب للاستخدام ضمن روتين العناية بالبشرة',sizes:['مقاس واحد'],colors:['وردي لؤلؤي'],colorVariants:[{name:'وردي لؤلؤي',hex:'#efc5c8',image:'/rosjo/images/products/cleanser/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-shea-butter',name:'زبدة الشيا الخام النقية | Shea Butter',category:'Rosjo',price:220,compareAtPrice:280,image:'/rosjo/images/products/shea-butter/image-1.png',images:['/rosjo/images/products/shea-butter/image-1.png','/rosjo/images/products/shea-butter/image-2.png','/rosjo/images/products/shea-butter/image-3.png'],description:'زبدة شيا طبيعية وخام تساعد على ترطيب البشرة وتغذيتها والحفاظ على نعومتها ويمكن استخدامها للعناية بالبشرة والشعر والمناطق الجافة ضمن روتين العناية اليومية',sizes:['مقاس واحد'],colors:['عاجي روزجو'],colorVariants:[{name:'عاجي روزجو',hex:'#f3e8db',image:'/rosjo/images/products/shea-butter/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-conditioner',name:'بلسم روزجو المغذي للشعر | Conditioner',category:'Rosjo',price:280,compareAtPrice:360,image:'/rosjo/images/products/conditioner/image-1.png',images:['/rosjo/images/products/conditioner/image-1.png','/rosjo/images/products/conditioner/image-2.png','/rosjo/images/products/conditioner/image-3.png'],description:'بلسم مغذي يساعد على ترطيب الشعر وتنعيمه وفك التشابك وتحسين سهولة التصفيف ويمنح الشعر ملمسًا أكثر نعومة ومظهرًا صحيًا',sizes:['مقاس واحد'],colors:['وردي حريري'],colorVariants:[{name:'وردي حريري',hex:'#d98f98',image:'/rosjo/images/products/conditioner/image-1.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-hair-care-bundle',name:'باقة العناية بالشعر | Hair Care Bundle',category:'Rosjo',price:650,compareAtPrice:750,image:'/rosjo/images/bundles/hair-care-bundle/bundle.png',images:['/rosjo/images/bundles/hair-care-bundle/bundle.png'],description:'باقة متكاملة للعناية بالشعر وتحتوي على معزز نمو بصيلات الشعر Follicle Booster وسيروم الشعر الحريري Hair Serum وزبدة الشيا Shea Butter وتساعد على العناية بالشعر من الجذور وتقليل الجفاف والهيشان والحفاظ على ترطيب ونعومة الشعر',sizes:['مقاس واحد'],colors:['وردي روزجو'],colorVariants:[{name:'وردي روزجو',hex:'#d98f98',image:'/rosjo/images/bundles/hair-care-bundle/bundle.png',stock:20}],stock:20,active:true,demo:false,featured:true},
 {id:'rosjo-skin-care-bundle',name:'باقة العناية بالبشرة | Skin Care Bundle',category:'Rosjo',price:400,compareAtPrice:480,image:'/rosjo/images/bundles/skin-care-bundle/bundle.png',images:['/rosjo/images/bundles/skin-care-bundle/bundle.png'],description:'باقة مخصصة للعناية بالبشرة وتحتوي على غسول الوجه Facial Cleanser ومرطب الوجه Moisturizer وتساعد على تنظيف البشرة وترطيبها والحفاظ على نعومتها ونضارتها ضمن روتين يومي للعناية بالبشرة',sizes:['مقاس واحد'],colors:['وردي فاتح'],colorVariants:[{name:'وردي فاتح',hex:'#e7a5b5',image:'/rosjo/images/bundles/skin-care-bundle/bundle.png',stock:20}],stock:20,active:true,demo:false,featured:true}
];
export const demoProducts: Product[] = [
 {id:'demo-1',name:'قميص لينن أوفر سايز',category:'ملابس',price:650,image:'/images/collection.png',description:'قميص خفيف بقصّة واسعة ولمسة يومية سهلة التنسيق.',sizes:['S','M','L','XL'],colors:['أوف وايت','أسود'],stock:0,active:true,demo:true,featured:true},
 {id:'demo-2',name:'شنطة يومك المفضلة',category:'شنط',price:790,image:'/images/collection.png',description:'شنطة عملية بتفاصيل بسيطة تناسب مشاويرك اليومية.',sizes:['مقاس واحد'],colors:['أسود'],stock:0,active:true,demo:true,featured:true},
 {id:'demo-3',name:'لوك بسيط لكل خروجة',category:'ملابس',price:950,image:'/images/editorial.png',description:'اختيار هادئ وسهل تكمّلي به إطلالتك بطريقتك.',sizes:['S','M','L'],colors:['أوف وايت'],stock:0,active:true,demo:true,featured:true},
 {id:'demo-4',name:'شنطة بتفاصيل مميزة',category:'شنط',price:850,image:'/images/collection.png',description:'تصميم أنيق يضيف لمسة مختلفة للوكك.',sizes:['مقاس واحد'],colors:['أسود'],stock:0,active:true,demo:true,featured:false}
];
export const money = (v:number) => new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(v)+' ج.م';
const colorHexes:Record<string,string>={'أسود':'#111111','ابيض':'#f7f5ef','أبيض':'#f7f5ef','أوف وايت':'#e9e1d4','بيج':'#c9b39b','بني':'#6d4734','برتقالي':'#f26b38','أحمر':'#d5473f','وردي':'#e7a5b5','أزرق':'#4d78b8','أخضر':'#6f9674','رمادي':'#8c8c8c'};
export function getColorVariants(product:Product):ColorVariant[]{
  if(product.colorVariants?.length)return product.colorVariants;
  return product.colors.map(name=>({name,hex:colorHexes[name]||'#b8aa9a',stock:product.stock}));
}
export function getColorVariant(product:Product,name:string){return getColorVariants(product).find(v=>v.name===name);}
export function selectionStock(product:Product,size:string,color:string){
  const colorStock=getColorVariant(product,color)?.stock;
  const sizeStock=product.sizeStock?.[size];
  const values=[product.stock,sizeStock,colorStock].filter((v):v is number=>typeof v==='number');
  return values.length?Math.min(...values):product.stock;
}



