'use client';
import { useEffect, useState } from 'react';
import { Pencil, ShieldCheck, Trash2, UserPlus } from 'lucide-react';
import { toast } from 'sonner';
const options=[['products','المنتجات'],['orders','الطلبات'],['analytics','التحليلات والتقارير'],['coupons','الكوبونات'],['shipping','المحافظات والتوصيل'],['settings','الإعدادات والأقسام']] as const;
type User={id:string;email:string;name:string;permissions:string[];active:boolean};
type AdminData={supervisors?:User[]};
export default function TeamPanel(){
 const [users,setUsers]=useState<User[]>([]); const [editing,setEditing]=useState(''); const [form,setForm]=useState({name:'',email:'',password:'',permissions:['products','orders']});
 async function load(){const r=await fetch('/api/admin');const v=await r.json() as AdminData;if(r.ok)setUsers(v.supervisors||[]);} useEffect(()=>{void load();},[]);
 function toggle(key:string){setForm(f=>({...f,permissions:f.permissions.includes(key)?f.permissions.filter(x=>x!==key):[...f.permissions,key]}));}
 async function add(e:React.FormEvent){e.preventDefault();if(!window.confirm(editing?'تأكيد حفظ صلاحيات المشرف؟':'تأكيد إضافة المشرف بالصلاحيات المحددة؟'))return;const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:editing?'updateSupervisor':'supervisor',...(editing?{id:editing}:{}),...form})});const v=await r.json() as {error?:string};if(!r.ok){toast.error(v.error);return;}toast.success(editing?'اتحفظت بيانات المشرف':'اتضاف المشرف');setEditing('');setForm({name:'',email:'',password:'',permissions:['products','orders']});await load();}
 function editUser(user:User){setEditing(user.id);setForm({name:user.name,email:user.email,password:'',permissions:user.permissions});}
 async function remove(id:string){if(!window.confirm('حذف المشرف وإلغاء وصوله؟'))return;const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'removeSupervisor',id})});if(r.ok){toast.success('اتحذف المشرف');await load();}else toast.error('تعذر الحذف');}
 return <main className="standalone-admin-page"><div className="admin-heading"><div><p className="eyebrow">BE3A / TEAM</p><h1>المشرفون والصلاحيات</h1><p>أضيفي مشرفين مع صلاحيات محددة، والمالك يظل صاحب كل الصلاحيات.</p></div></div><section className="admin-card"><h2><UserPlus size={19}/>{editing?'تعديل المشرف':'إضافة مشرف'}</h2><form className="form-grid" onSubmit={add}><label>الاسم<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الإيميل<input required type="email" dir="ltr" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>كلمة المرور<input required={!editing} minLength={editing?0:10} type="password" dir="ltr" placeholder={editing?'اتركيها فارغة للإبقاء على كلمة المرور':'10 أحرف على الأقل'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="permission-picker full"><strong>الصلاحيات</strong>{options.map(([key,label])=><label key={key}><input type="checkbox" checked={form.permissions.includes(key)} onChange={()=>toggle(key)}/>{label}</label>)}</div><button type="submit" className="primary full">{editing?'حفظ بيانات المشرف':'إضافة المشرف'}</button>{editing&&<button type="button" className="secondary full" onClick={()=>{setEditing('');setForm({name:'',email:'',password:'',permissions:['products','orders']});}}>إلغاء التعديل</button>}</form></section><section className="admin-card"><h2><ShieldCheck size={19}/>المشرفون الحاليون</h2>{users.length?<div className="coupon-list">{users.map(u=><div className="coupon-row" key={u.id}><strong>{u.name}</strong><span dir="ltr">{u.email}</span><span>{u.permissions.map(p=>options.find(x=>x[0]===p)?.[1]).filter(Boolean).join('، ')}</span><button onClick={()=>editUser(u)} aria-label={'تعديل '+u.name}><Pencil size={17}/></button><button onClick={()=>void remove(u.id)} aria-label={'حذف '+u.name}><Trash2 size={17}/></button></div>)}</div>:<p className="notification-empty">مفيش مشرفين إضافيين.</p>}</section></main>;
}
