'use client';
import { useEffect, useState } from 'react';
import { Pencil, Plus, Tags, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import type { Settings } from '@/lib/catalog';
type Data={settings?:Settings;error?:string};
export default function CategoriesPanel(){
  const [settings,setSettings]=useState<Settings|null>(null); const [name,setName]=useState(''); const [editing,setEditing]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch('/api/admin');const v=await r.json() as Data;if(r.ok&&v.settings)setSettings(v.settings);else toast.error(v.error||'تعذر تحميل الأقسام');}
  useEffect(()=>{void load();},[]);
  function startEdit(category:string){setEditing(category);setName(category);}
  function cancelEdit(){setEditing('');setName('');}
  async function saveCategory(e:React.FormEvent){e.preventDefault();if(!settings||!name.trim())return;const next=name.trim();if(settings.categories.includes(next)&&next!==editing){toast.error('اسم القسم موجود بالفعل');return;}const categories=editing?settings.categories.map(c=>c===editing?next:c):[...settings.categories,next];const categoryImages={...settings.categoryImages};if(editing&&editing!==next&&categoryImages[editing]){categoryImages[next]=categoryImages[editing];delete categoryImages[editing];}if(!window.confirm(editing?'تأكيد تعديل اسم القسم؟':'تأكيد إضافة القسم؟'))return;setBusy(true);try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',data:{...settings,categories,categoryImages}})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error);toast.success(editing?'اتعدل القسم':'اتضاف القسم');setSettings({...settings,categories,categoryImages});cancelEdit();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function remove(category:string){if(!settings||settings.categories.length<=1){toast.error('لازم يفضل قسم واحد على الأقل');return;}if(!window.confirm('حذف القسم؟ المنتجات الحالية داخله لن تُحذف، لكن اختاري لها قسمًا آخر قبل تعديلها.'))return;setBusy(true);try{const categories=settings.categories.filter(c=>c!==category);const categoryImages={...settings.categoryImages};delete categoryImages[category];const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',data:{...settings,categories,categoryImages}})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error);setSettings({...settings,categories,categoryImages});toast.success('اتحذف القسم');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  if(!settings)return <main className="standalone-admin-page"><div className="admin-card">جاري تحميل الأقسام…</div></main>;
  return <main className="standalone-admin-page"><div className="admin-heading"><div><p className="eyebrow">BE3A / CATEGORIES</p><h1>أقسام المتجر</h1><p>أضيفي الأقسام وعدّلي أسماءها أو احذفيها. المنتجات لا تُحذف مع القسم.</p></div></div><section className="admin-card"><h2><Plus size={19}/>{editing?'تعديل القسم':'إضافة قسم'}</h2><form className="category-form" onSubmit={saveCategory}><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: ملابس"/><button className="primary" disabled={busy}>{editing?'حفظ الاسم':'إضافة القسم'}</button>{editing&&<button type="button" className="secondary" onClick={cancelEdit}>إلغاء</button>}</form></section><section className="admin-card"><h2><Tags size={19}/>الأقسام الحالية</h2><div className="category-list">{settings.categories.map(category=><div className="category-row" key={category}><strong>{category}</strong><div><button aria-label={'تعديل '+category} onClick={()=>startEdit(category)}><Pencil size={17}/></button><button aria-label={'حذف '+category} onClick={()=>void remove(category)}><Trash2 size={17}/></button></div></div>)}</div></section></main>;
}
