import { db,readSettings,readProducts,readOrders } from '@/lib/server';
import { isAdmin,sameOrigin,json } from '@/lib/auth';
import { addSupervisor, canManage, currentAdmin, listSupervisors, removeSupervisor, updateSupervisor, loginPassword, adminEmail, changeCurrentPassword } from '@/lib/admin-auth';
import { deleteCoupon, listCoupons, readReports, readReportsRange, saveCoupon } from '@/lib/commerce';
import { settingsSchema,productSchema } from '@/lib/validation';
import { notify } from '@/lib/analytics';
import { defaults } from '@/lib/catalog';
export async function GET(req:Request){if(!await isAdmin())return json({error:'الدخول مخصص لإدارة بيعة فقط'},403);try{const url=new URL(req.url);const requested=Number(url.searchParams.get('days'));const days=[7,30,90,365].includes(requested)?requested:30;const period=url.searchParams.get('period');const from=url.searchParams.get('from');const to=url.searchParams.get('to');const month=url.searchParams.get('month');let reports;if(from&&to){const start=new Date(`${from}T00:00:00`).getTime(),end=new Date(`${to}T23:59:59.999`).getTime();reports=Number.isFinite(start)&&Number.isFinite(end)&&start<=end?await readReportsRange(start,end):await readReports(days);}else if(month&&/^\d{4}-\d{2}$/.test(month)){const [year,monthNumber]=month.split('-').map(Number);reports=await readReportsRange(new Date(year,monthNumber-1,1).getTime(),new Date(year,monthNumber,1).getTime()-1);}else if(period==='current-month'){const now=new Date();reports=await readReportsRange(new Date(now.getFullYear(),now.getMonth(),1).getTime(),Date.now());}else if(period==='last-month'){const now=new Date();reports=await readReportsRange(new Date(now.getFullYear(),now.getMonth()-1,1).getTime(),new Date(now.getFullYear(),now.getMonth(),1).getTime()-1);}else reports=await readReports(days);const viewer=await currentAdmin();return json({viewer:viewer?{email:viewer.email,role:viewer.role,permissions:viewer.permissions}:null,settings:await readSettings(),products:await readProducts(true),orders:await readOrders(),supervisors:await listSupervisors(),coupons:await listCoupons(),reports});}catch(e){console.error('Admin load failed',e);return json({error:'تعذر تحميل البيانات. حاولي مرة تانية.'},503);}}
export async function POST(req:Request){if(!await isAdmin())return json({error:'غير مصرح'},403);if(!sameOrigin(req))return json({error:'طلب غير مسموح'},403);if(Number(req.headers.get('content-length'))>65000)return json({error:'البيانات كبيرة جدًا'},413);try{const raw=await req.text();if(raw.length>65000)return json({error:'البيانات كبيرة جدًا'},413);const b=JSON.parse(raw);
if(b.action==='settings'){if(!await canManage('settings')&&!await canManage('shipping'))return json({error:'صلاحيتك لا تسمح بتعديل الإعدادات'},403);const v=settingsSchema.parse(b.data);await db().prepare('INSERT INTO settings(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(JSON.stringify(v)).run();}
else if(b.action==='product'){if(!await canManage('products'))return json({error:'صلاحيتك لا تسمح بتعديل المنتجات'},403);const p=productSchema.parse(b.data);const s=await readSettings();if(!s.categories.includes(p.category))return json({error:'اختاري قسمًا موجودًا في إعدادات المتجر'},400);const result=await db().prepare('INSERT INTO products(id,data,price,stock,active,demo,updated) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,price=excluded.price,stock=excluded.stock,active=excluded.active,demo=excluded.demo,updated=products.updated+1 WHERE products.updated=?').bind(p.id,JSON.stringify(p),Math.round(p.price*100),p.stock,+p.active,+p.demo,Date.now(),p.revision??-1).run();if(!result.meta.changes)return json({error:'المخزون أو المنتج اتغيّر أثناء التعديل. اقفلي التعديل وحدّثي البيانات قبل الحفظ.'},409);if(p.active&&!p.demo&&p.stock<=5)try{await notify('product','مخزون منخفض: '+p.name,`متبقي ${p.stock} قطعة فقط`,'/admin/products');}catch(e){console.error('Notification failed',e);}}
else if(b.action==='archive'){if(!await canManage('products'))return json({error:'صلاحيتك لا تسمح بتعديل المنتجات'},403);if(typeof b.id!=='string')return json({error:'منتج غير صحيح'},400);await db().prepare('UPDATE products SET active=0,updated=updated+1 WHERE id=?').bind(b.id).run();}
else if(b.action==='deleteProduct'){if(!await canManage('products'))return json({error:'صلاحيتك لا تسمح بحذف المنتجات'},403);if(typeof b.id!=='string')return json({error:'منتج غير صحيح'},400);const used=await db().prepare('SELECT COUNT(*) as count FROM order_items WHERE product_id=?').bind(b.id).first<{count:number}>();if(Number(used?.count))return json({error:'المنتج مرتبط بطلبات سابقة، اخفيه بدل حذفه للحفاظ على سجل الطلبات.'},409);const deleted=await db().prepare('DELETE FROM products WHERE id=?').bind(b.id).run();if(!deleted.meta.changes)return json({error:'المنتج غير موجود'},404);}
else if(b.action==='status'){if(!await canManage('orders'))return json({error:'صلاحيتك لا تسمح بتعديل الطلبات'},403);const next:Record<string,string[]>= {pending:['confirmed','cancelled'],confirmed:['shipped','delivered','cancelled'],shipped:['delivered','returned'],delivered:['returned'],returned:[],cancelled:[]};const current=await db().prepare('SELECT status FROM orders WHERE id=?').bind(String(b.id)).first<{status:string}>();if(!current||!next[current.status]?.includes(b.status))return json({error:'لا يمكن تغيير الطلب لهذه الحالة'},400);const restore=['cancelled','returned'].includes(String(b.status));if(restore){const items=await db().prepare('SELECT product_id,size,color,quantity FROM order_items WHERE order_id=?').bind(String(b.id)).all<any>();const products=await readProducts(true);const grouped=new Map<string,any>();for(const item of items.results){const p=products.find(x=>x.id===item.product_id);if(!p)continue;let next=grouped.get(p.id);if(!next){next={...p,sizeStock:{...p.sizeStock},colorVariants:p.colorVariants?.map((v:any)=>({...v}))};delete next.revision;grouped.set(p.id,next);}next.stock=Number(next.stock||0)+Number(item.quantity||0);if(next.sizeStock&&item.size)next.sizeStock[item.size]=Number(next.sizeStock[item.size]||0)+Number(item.quantity||0);if(next.colorVariants&&item.color){const v=next.colorVariants.find((x:any)=>x.name===item.color);if(v&&typeof v.stock==='number')v.stock+=Number(item.quantity||0);}}const statements=[db().prepare('UPDATE orders SET status=? WHERE id=? AND status=?').bind(b.status,b.id,current.status),...Array.from(grouped.values()).map((p:any)=>db().prepare('UPDATE products SET data=?,stock=?,updated=updated+1 WHERE id=?').bind(JSON.stringify(p),p.stock,p.id))];const results=await db().batch(statements);if(!results[0]?.meta?.changes)return json({error:'الطلب اتعدل بالفعل، حدّثي الصفحة'},409);}else{const result=await db().prepare('UPDATE orders SET status=? WHERE id=? AND status=?').bind(b.status,b.id,current.status).run();if(!result.meta.changes)return json({error:'الطلب اتعدل بالفعل، حدّثي الصفحة'},409);}}
else if(b.action==='deleteOrder'){if(!await canManage('orders'))return json({error:'صلاحيتك لا تسمح بحذف الطلبات'},403);const order=await db().prepare('SELECT status FROM orders WHERE id=?').bind(String(b.id)).first<{status:string}>();if(!order)return json({error:'الطلب غير موجود'},404);if(order.status!=='cancelled')return json({error:'لا يمكن حذف طلب غير ملغي. غيّري حالته إلى ملغي أولًا.'},409);await db().batch([db().prepare('DELETE FROM order_items WHERE order_id=?').bind(String(b.id)),db().prepare('DELETE FROM orders WHERE id=?').bind(String(b.id))]);}
else if(b.action==='supervisor'){if(!await canManage('team'))return json({error:'إدارة المشرفين متاحة للمالك فقط'},403);await addSupervisor(String(b.name),String(b.email),String(b.password),Array.isArray(b.permissions)?b.permissions.filter((x:any)=>typeof x==='string'):[]);}
else if(b.action==='updateSupervisor'){if(!await canManage('team'))return json({error:'إدارة المشرفين متاحة للمالك فقط'},403);await updateSupervisor(String(b.id),String(b.name),String(b.email),String(b.password||''),Array.isArray(b.permissions)?b.permissions.filter((x:any)=>typeof x==='string'):[]);}
else if(b.action==='removeSupervisor'){if(!await canManage('team'))return json({error:'إدارة المشرفين متاحة للمالك فقط'},403);await removeSupervisor(String(b.id));}
else if(b.action==='changePassword'){await changeCurrentPassword(String(b.currentPassword||''),String(b.newPassword||''));}
else if(b.action==='coupon'){if(!await canManage('coupons'))return json({error:'صلاحيتك لا تسمح بتعديل الكوبونات'},403);const d=b.data||{};const code=String(d.code||'').trim().toUpperCase();const kind=d.kind==='fixed'?'fixed':d.kind==='percent'?'percent':null;const scope=d.scope==='shipping'?'shipping':d.scope==='order'?'order':null;const value=Number(d.value),minSubtotal=Number(d.minSubtotal),usageLimit=Number(d.usageLimit);if(!/^[A-Z0-9_-]{2,40}$/.test(code)||!kind||!scope||!Number.isFinite(value)||value<=0||(kind==='percent'&&value>100)||!Number.isFinite(minSubtotal)||minSubtotal<0||!Number.isInteger(usageLimit)||usageLimit<0||usageLimit>10000000||((d.starts!==null&&d.starts!==undefined)&&!Number.isFinite(Number(d.starts)))||((d.expires!==null&&d.expires!==undefined)&&!Number.isFinite(Number(d.expires)))||(d.starts&&d.expires&&Number(d.starts)>Number(d.expires)))return json({error:'راجعي كود الخصم ونوعه وقيمته وفترة الصلاحية.'},400);await saveCoupon({...d,code,kind,scope,value,minSubtotal,usageLimit,used:Math.max(0,Math.floor(Number(d.used)||0)),starts:d.starts??null,expires:d.expires??null});}
else if(b.action==='deleteCoupon'){if(!await canManage('coupons'))return json({error:'صلاحيتك لا تسمح بتعديل الكوبونات'},403);await deleteCoupon(String(b.code));}
else if(b.action==='resetStore'){const owner=await currentAdmin();if(!owner||owner.role!=='owner')return json({error:'إعادة ضبط المتجر متاحة للمالك الأساسي فقط'},403);const password=String(b.password||'');const from=Number(b.from),to=Number(b.to);if(password.length<10||!Number.isFinite(from)||!Number.isFinite(to)||from>to||Date.now()<from||Date.now()>to)return json({error:'راجعي كلمة المرور والنافذة الزمنية لإعادة الضبط.'},400);try{await loginPassword(adminEmail(),password);}catch{return json({error:'كلمة مرور الإدارة غير صحيحة'},401);}const database=db();await database.batch([database.prepare('DELETE FROM order_items'),database.prepare('DELETE FROM orders'),database.prepare('DELETE FROM products'),database.prepare('DELETE FROM coupons'),database.prepare('DELETE FROM site_visits'),database.prepare('DELETE FROM admin_notifications'),database.prepare('INSERT INTO settings(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(JSON.stringify(defaults))]);}
else return json({error:'إجراء غير معروف'},400);return json({ok:true});
}catch(e){if(e instanceof SyntaxError|| (e as {name:string}).name==='ZodError')return json({error:'راجعي الحقول المطلوبة، الأسعار والروابط والمقاسات.'},400);console.error('Admin mutation failed',e);return json({error:'تعذر الحفظ. بياناتك لسه موجودة، حاولي مرة تانية.'},503);}}

