import { db,readSettings,readProducts,readOrders } from '@/lib/server';
import { isAdmin,sameOrigin,json } from '@/lib/auth';
import { settingsSchema,productSchema } from '@/lib/validation';
export async function GET(){if(!await isAdmin())return json({error:'الدخول مخصص لإدارة بيعة فقط'},403);try{return json({settings:await readSettings(),products:await readProducts(true),orders:await readOrders()});}catch(e){console.error('Admin load failed',e);return json({error:'تعذر تحميل البيانات. حاولي مرة تانية.'},503);}}
export async function POST(req:Request){if(!await isAdmin())return json({error:'غير مصرح'},403);if(!sameOrigin(req))return json({error:'طلب غير مسموح'},403);if(Number(req.headers.get('content-length'))>65000)return json({error:'البيانات كبيرة جدًا'},413);try{const raw=await req.text();if(raw.length>65000)return json({error:'البيانات كبيرة جدًا'},413);const b=JSON.parse(raw);
if(b.action==='settings'){const v=settingsSchema.parse(b.data);await db().prepare('INSERT INTO settings(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(JSON.stringify(v)).run();}
else if(b.action==='product'){const p=productSchema.parse(b.data);const s=await readSettings();if(!s.categories.includes(p.category))return json({error:'اختاري قسمًا موجودًا في إعدادات المتجر'},400);const result=await db().prepare('INSERT INTO products(id,data,price,stock,active,demo,updated) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,price=excluded.price,stock=excluded.stock,active=excluded.active,demo=excluded.demo,updated=products.updated+1 WHERE products.updated=?').bind(p.id,JSON.stringify(p),Math.round(p.price*100),p.stock,+p.active,+p.demo,Date.now(),p.revision??-1).run();if(!result.meta.changes)return json({error:'المخزون أو المنتج اتغيّر أثناء التعديل. اقفلي التعديل وحدّثي البيانات قبل الحفظ.'},409);}
else if(b.action==='archive'){if(typeof b.id!=='string')return json({error:'منتج غير صحيح'},400);await db().prepare('UPDATE products SET active=0,updated=updated+1 WHERE id=?').bind(b.id).run();}
else if(b.action==='status'){const next:Record<string,string[]>= {pending:['confirmed','cancelled'],confirmed:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[]};const current=await db().prepare('SELECT status FROM orders WHERE id=?').bind(String(b.id)).first<{status:string}>();if(!current||!next[current.status]?.includes(b.status))return json({error:'لا يمكن تغيير الطلب لهذه الحالة'},400);const result=await db().prepare('UPDATE orders SET status=? WHERE id=? AND status=?').bind(b.status,b.id,current.status).run();if(!result.meta.changes)return json({error:'الطلب اتعدل بالفعل، حدّثي الصفحة'},409);}
else return json({error:'إجراء غير معروف'},400);return json({ok:true});
}catch(e){if(e instanceof SyntaxError|| (e as {name:string}).name==='ZodError')return json({error:'راجعي الحقول المطلوبة، الأسعار والروابط والمقاسات.'},400);console.error('Admin mutation failed',e);return json({error:'تعذر الحفظ. بياناتك لسه موجودة، حاولي مرة تانية.'},503);}}

