import {db,readSettings,readProducts} from '@/lib/server';
import {json,sameOrigin} from '@/lib/auth';
import {orderSchema} from '@/lib/validation';
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'طلب غير مسموح'},403);if(Number(req.headers.get('content-length'))>20000)return json({error:'طلب كبير جدًا'},413);try{const raw=await req.text();if(raw.length>20000)return json({error:'طلب كبير جدًا'},413);const data=orderSchema.parse(JSON.parse(raw));const database=db();
const existing=await database.prepare('SELECT reference,total FROM orders WHERE id=?').bind(data.id).first();if(existing)return json({ok:true,...existing});
const s=await readSettings();if(!s.checkoutEnabled)return json({error:'استقبال الطلبات متوقف حاليًا. تواصلي مع بيعة.'},409);const delivery=s.shipping.find(x=>x.name===data.governorate);if(!delivery)return json({error:'اختاري منطقة شحن متاحة'},400);
const ip=req.headers.get('cf-connecting-ip')||'local';const hashed=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip)))).map(n=>n.toString(16).padStart(2,'0')).join('');const bucket=Math.floor(Date.now()/600000);const key=hashed+':'+bucket;
const limited=await database.batch([database.prepare('INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1').bind(key,Date.now()+1200000),database.prepare('SELECT count FROM rate_limits WHERE id=?').bind(key),database.prepare('DELETE FROM rate_limits WHERE expires<?').bind(Date.now())]);if(Number((limited[1].results[0] as {count:number}).count)>10)return json({error:'طلبات كتير في وقت قصير. استني شوية وحاولي تاني.'},429);
const products=await readProducts();const lines=data.items.map(i=>{const p=products.find(p=>p.id===i.productId);if(!p||p.demo||p.stock<i.quantity||!p.sizes.includes(i.size)||!p.colors.includes(i.color))throw new Error('UNAVAILABLE');return {...i,name:p.name,price:Math.round(p.price*100)};});
const shipping=Math.round(delivery.price*100);const total=lines.reduce((n,i)=>n+i.price*i.quantity,shipping);const ref='B3-'+data.id.slice(0,8).toUpperCase();
const statements=[database.prepare('INSERT INTO orders(id,reference,customer,phone,address,governorate,notes,shipping,total,status,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(data.id,ref,data.customer,data.phone,data.address,data.governorate,data.notes,shipping,total,'pending',Date.now()),...lines.map(i=>database.prepare('INSERT INTO order_items(id,order_id,product_id,name,size,color,quantity,price) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),data.id,i.productId,i.name,i.size,i.color,i.quantity,i.price))];
await database.batch(statements);return json({ok:true,reference:ref,total},201);
}catch(e){const msg=String(e);if(msg.includes('UNIQUE constraint failed: orders.id'))return json({error:'الطلب اتسجل بالفعل. اضغطي تأكيد مرة تانية لاسترجاع رقم الطلب.'},409);if(msg.includes('UNAVAILABLE')||msg.includes('OUT_OF_STOCK'))return json({error:'كمية أو اختيار من المنتجات مبقاش متاح. راجعي الشنطة وحدّثي الصفحة.'},409);if(e instanceof SyntaxError||(e as {name:string}).name==='ZodError')return json({error:'راجعي الاسم والموبايل المصري والعنوان واختيارات المنتجات.'},400);console.error('Order failed',e);return json({error:'تعذر تأكيد الطلب. حاولي تاني بنفس الشنطة.'},503);}}
